	TITLE	D:\Klingons\Render\Src\UnTest.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT ??_C@_02DILL@?$CFs?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_03IDPP@new?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_09NHFI@NameEntry?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0CD@IOIP@UObject?5assignment?5operator?5call@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0CJ@JMDF@UObject?5copy?5constructor?5operato@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EN@PEDE@Check?5failed?3?5i?$DO?$DN0?5?$CG?$CG?5i?$DMGetMax?$CI?$CJ@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EA@NHOH@Check?5failed?3?5Class?5?$FLFile?3?4?4?2?4?4?2@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0CB@LMKJ@FProperty?3?3Init?3?5invalid?5type?5?$CFi@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_03FBGG@F?$CFs?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_05DGIH@Actor?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_01PFH@A?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_01MHL@U?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_04DCMN@?$CFs?$CFs?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0FO@DCOG@Check?5failed?3?5Defaults?4Num?$CI?$CJ?$DN?$DNPr@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EI@FNEO@Check?5failed?3?5Defaults?4Num?$CI?$CJ?5?$FLFi@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_06PNHD@Vector?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_08GCLC@Rotation?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0FF@JPBM@Check?5failed?3?5InType?$DN?$DNCPT_Object@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EM@PLEE@Check?5failed?3?5InType?$DN?$DNCPT_Struct@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EK@EHMC@Check?5failed?3?5InType?$DN?$DNCPT_Byte?5?$FL@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0O@OIEJ@Unhashed?5item?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0FH@FKFD@Check?5failed?3?5ActiveChunks?$DM?$DNMem?9@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_04FKCF@?$CI?$CFs?$CJ?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EK@LHBB@Check?5failed?3?5i?$DM?$CIDWORD?$CJNumBits?5?$FL@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EI@EGOH@Check?5failed?3?5i?$DMSide?$CG?$CGj?$DMSide?5?$FLFi@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EA@FMAN@Check?5failed?3?5Brush?5?$FLFile?3?4?4?2?4?4?2@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EA@JAE@Check?5failed?3?5Other?5?$FLFile?3?4?4?2?4?4?2@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EH@GBPM@Check?5failed?3?5Other?9?$DOBrush?5?$FLFile@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_05BFNK@Index?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EE@NGOK@Check?5failed?3?5Num?$CI?$CJ?$DO?$DN2?5?$FLFile?3?4?4?2@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EL@ELKL@Check?5failed?3?5Actors?$CI1?$CJ?$CB?$DNNULL?5?$FLF@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0FC@PNII@Check?5failed?3?5Actors?$CI1?$CJ?9?$DOBrush?$CB?$DN@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BE@FGCD@Actor?5not?5found?3?5?$CFs?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EF@LODM@Check?5failed?3?5Actors?$CI0?$CJ?5?$FLFile?3?4?4@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0GD@NDIK@Check?5failed?3?5Actors?$CI0?$CJ?9?$DOIsA?$CIALe@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_09DEGN@HHitProxy?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_08CHIE@HBspSurf?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_06PDIP@HActor?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_07IDGH@HCoords?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
drectve	SEGMENT DWORD USE32 PUBLIC ''
drectve	ENDS
;	COMDAT ??_C@_0DP@NFMJ@Check?5failed?3?5Index?$DO?$DN0?5?$FLFile?3?4?4?2@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EG@OGEE@Check?5failed?3?5Index?$DM?$DNArrayNum?5?$FLF@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0EM@GAIE@Check?5failed?3?5Index?$CLCount?$DM?$DNArray@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
xdata$x	SEGMENT DWORD USE32 PUBLIC 'CONST'
xdata$x	ENDS
;	COMDAT ?appFloor@@YAHM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?appCycles@@YAKXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?appToUpper@@YADD@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2@YAPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??3@YAXPAX@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAE@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAG@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAF@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAK@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AA_K@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FIteratorList@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FIteratorList@@QAE@PAU0@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??EFObjectIterator@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUPackage@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUTextBuffer@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUEnum@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUStruct@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAPAVUClass@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUClass@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??EFPropertyIterator@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GHash@@YAKK@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2@YAPAXIAAVFMemStack@@HH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?FSnap@@YAMMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?FSheerSnap@@YAMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?FAddAngleConfined@@YAGHHHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??D@YA?AVFVector@@MABV0@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAVFVector@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAVFPlane@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?ReduceAngle@@YAHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?FPointPlaneDist@@YAMABVFVector@@00@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?FParallel@@YAHABVFVector@@0@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?IsCsg@FBspNode@@QBEHK@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAVFZoneProperties@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUBspNodes@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUBspSurfs@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUPolys@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUVectors@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUVerts@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUBitArray@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUBitMatrix@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUPalette@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAPAVUTexture@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUTexture@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUFont@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FIteratorActorList@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FIteratorActorList@@QAE@PAU0@PAVAActor@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUPrimitive@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUModel@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAPAVAActor@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??Damage@AActor@@QAEXHPAVAPawn@@VFVector@@1VFName@@@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??Landed@AActor@@QAEXVFVector@@@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??HitWall@AActor@@QAEXVFVector@@PAV2@@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAActor@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??ClientHearSound@APawn@@QAEXPAVAActor@@HPAVUSound@@VFVector@@MMM@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAPawn@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??PlayerCalcView@APlayerPawn@@QAEXAAPAVAActor@@AAVFVector@@AAVFRotation@@@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0__unnamed@?1??ClientPush@APlayerPawn@@QAEXVFVector@@PAVAActor@@0@Z@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAPlayerPawn@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_H@YGXPAXIHP6EX0@Z@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GACamera@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAScout@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GABrush@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAMover@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAZoneInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAWarpZoneInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GASkyZoneInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GALevelInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAGameInfo@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAMenu@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAHUD@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GATriggers@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GATrigger@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAInventory@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAWeapon@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAKeypoint@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAInterpolationPoint@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAProjectile@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GADecoration@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GANavigationPoint@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAWarpZoneMarker@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAButtonMarker@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GATriggerMarker@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAInventorySpot@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAPlayerStart@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GATeleporter@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GAPathNode@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1FCollisionHashBase@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFCollisionHashBase@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GULevel@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??EFStaticBrushIterator@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1UInput@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2UInput@@SAPAXIPAW4EInternal@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUInput@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUGameEngine@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUCanvas@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAUFMeshUV@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAUFMeshAnimNotify@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FMeshAnimNotify@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUMesh@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUSound@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GUMusic@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FTransform@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FOutVector@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FTransSample@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FTransTexture@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FSpan@@QAE@HH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0FDynamicItem@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Filter@FDynamicItem@@UAEXPAVUViewport@@PAUFSceneNode@@HH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?PreRender@FDynamicItem@@UAEXPAVUViewport@@PAUFSceneNode@@PAVFSpanBuffer@@HPAUFVolActorLink@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1URender@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2URender@@SAPAXIPAW4EInternal@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GURender@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_EURender@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@D@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@D@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@D@@QAEAADH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@D@@QBEABDH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@D@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Empty@?$TArray@D@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Shrink@?$TArray@D@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?AddItem@?$TArray@D@@QAEHABD@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Add@?$TArray@D@@QAEHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?SetSize@?$TArray@D@@QAEXH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@PAUFNameEntry@@@@QAEAAPAUFNameEntry@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@PAUFNameEntry@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@H@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@H@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@PAVUObject@@@@QAEAAPAVUObject@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@PAVUObject@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFString@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFProperty@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFProperty@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@VFProperty@@@@QAEAAVFProperty@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@VFProperty@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Empty@?$TArray@VFProperty@@@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFName@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFName@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@UFConst@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFConst@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFStackNode@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFStackNode@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@VFStackNode@@@@QAEAAVFStackNode@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFDependency@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFDependency@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@E@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@E@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@E@@QAEAAEH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@E@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Add@?$TArray@E@@QAEHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@K@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@K@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@K@@QAEAAKH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Add@?$TArray@K@@QAEHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFColor@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFColor@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@VFColor@@@@QAEAAVFColor@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMipmap@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@UFMipmap@@@@QAEAAUFMipmap@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@UFMipmap@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFFontCharacter@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFLightMapIndex@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFLightMapIndex@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@VFLightMapIndex@@@@QAEAAVFLightMapIndex@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@VFLightMapIndex@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFBox@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFBox@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFLeaf@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFLeaf@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@PAVAActor@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@PAVAActor@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@VFReachSpec@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFReachSpec@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@PAVUViewport@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$TArray@UFMeshAnimNotify@@@@QAE@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMeshAnimNotify@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMeshVert@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMeshTri@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMeshAnimSeq@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@UFMeshAnimSeq@@@@QAEAAUFMeshAnimSeq@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@UFMeshAnimSeq@@@@QBEABUFMeshAnimSeq@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@UFMeshAnimSeq@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@UFMeshVertConnect@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@VFSphere@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$TArray@PAVUTexture@@@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@PAVUTexture@@@@QAEAAPAVUTexture@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@D@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@H@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFString@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFProperty@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFName@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFConst@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFStackNode@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFDependency@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@E@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Align@@YAPAEQAEH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Abs@@YAMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Clamp@@YAMMMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Sgn@@YAMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Min@@YAMMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Max@@YAMMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Square@@YAMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Abs@@YANN@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Square@@YANN@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAV?$TArray@E@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@K@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Clamp@@YAHHHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFColor@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMipmap@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFFontCharacter@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFLightMapIndex@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFBox@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFLeaf@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@PAVAActor@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Clamp@@YANNNN@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFReachSpec@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@PAVUViewport@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMeshAnimNotify@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??6@YAAAVFArchive@@AAV0@AAV?$TArray@UFMeshAnimNotify@@@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMeshVert@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMeshTri@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMeshAnimSeq@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@UFMeshVertConnect@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@VFSphere@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Remove@?$TArray@PAVUTexture@@@@QAEXHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFString@@QAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFConst@@QAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFStackNode@@QAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFMipmap@@QAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GFMeshAnimSeq@@QAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1FMeshAnimSeq@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@VFString@@@@QAEAAVFString@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@UFConst@@@@QAEAAUFConst@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Empty@?$TArray@E@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??R?$TArray@UFMeshAnimNotify@@@@QAEAAUFMeshAnimNotify@@H@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Num@?$TArray@UFMeshAnimNotify@@@@QBEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Empty@?$TArray@UFMeshAnimNotify@@@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2@YAPAXIAAV?$TArray@E@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??2@YAPAXIAAV?$TArray@UFMeshAnimNotify@@@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Add@?$TArray@UFMeshAnimNotify@@@@QAEHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFConst@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7URender@@6BFExec@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@K@@QAEAAKH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@D@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUCanvas@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAInventory@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAV?$TArray@E@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFDependency@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_R0PAX@8
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ?OutXMinTab@?1??ComputeOutcode@FTransform@@QAEXPBUFSceneNode@@@Z@4PBEB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Add@?$TArray@E@@QAEHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFPoly@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFFontCharacter@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@E@@QAEAAEH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??AddItem@?$TArray@D@@QAEHABD@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFProperty@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIPBD@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?Half@?1??appFloor@@YAHM@Z@4MA
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_7UInput@@6BUObject@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT __CT??_R0PAX@84
xdata$x	SEGMENT DWORD USE32 PUBLIC 'CONST'
xdata$x	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMeshAnimNotify@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Empty@?$TArray@E@@QAEXXZ@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFColor@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??AllocateNameEntry@@YAPAUFNameEntry@@PBDKKPAU2@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@PAVUObject@@@@QAEAAPAVUObject@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFGuid@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SULevel@@6BUDatabase@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFBox@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAPawn@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUVectors@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SABrush@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFVert@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUPrimitive@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAPlayerPawn@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@UFMeshAnimNotify@@@@QAEAAUFMeshAnimNotify@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAPlayerStart@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???3@YAXPAX@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAWeapon@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_R0PAD@8
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_SAPathNode@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAMover@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Shrink@?$TArray@D@@QAEXXZ@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7URender@@6BUObject@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAActor@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUEnum@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Add@?$TArray@K@@QAEHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Empty@?$TArray@UFMeshAnimNotify@@@@QAEXXZ@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@E@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SANavigationPoint@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@VFStackNode@@@@QAEAAVFStackNode@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUSound@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMeshVert@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUMesh@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAZoneInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAButtonMarker@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAGameInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SATriggers@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAUFMipmap@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUBspSurfs@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@PAVUViewport@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Add@?$TArray@D@@QAEHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@UFMeshAnimSeq@@@@QAEAAUFMeshAnimSeq@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SATeleporter@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFZoneProperties@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAScout@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SASkyZoneInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUBspNodes@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7FDynamicSprite@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUBitMatrix@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7FDynamicItem@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUGameEngine@@6BUObject@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFLeaf@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFReachSpec@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@UFMipmap@@@@QAEAAUFMipmap@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFBspNode@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAKeypoint@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUPackage@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT __CT??_R0PAD@84
xdata$x	SEGMENT DWORD USE32 PUBLIC 'CONST'
xdata$x	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFBspSurf@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@D@@QAEAADH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMeshTri@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUPalette@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@VFProperty@@@@QAEAAVFProperty@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUMusic@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAHUD@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@VFColor@@@@QAEAAVFColor@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIAAVFMemStack@@W4EMemOned@@HH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFSphere@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@VFLightMapIndex@@@@QAEAAVFLightMapIndex@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFLightMapIndex@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFStackNode@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAWarpZoneMarker@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SATriggerMarker@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SADecoration@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAInterpolationPoint@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUFont@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUPolys@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIAAVFMemStack@@HH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Add@?$TArray@UFMeshAnimNotify@@@@QAEHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@PAVAActor@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMipmap@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7UInput@@6BFExec@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIAAV?$TArray@E@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUBitArray@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Empty@?$TArray@D@@QAEXXZ@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SATrigger@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?OutYMinTab@?1??ComputeOutcode@FTransform@@QAEXPBUFSceneNode@@@Z@4PBEB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@UFConst@@@@QAEAAUFConst@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXI@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@PAVUTexture@@@@QAEAAPAVUTexture@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?OutXMaxTab@?1??ComputeOutcode@FTransform@@QAEXPBUFSceneNode@@@Z@4PBEB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFName@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7FCollisionHashBase@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAMenu@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUStruct@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@VFString@@@@QAEAAVFString@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFFontCharacter@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?OutYMaxTab@?1??ComputeOutcode@FTransform@@QAEXPBUFSceneNode@@@Z@4PBEB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUVerts@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIAAV?$TArray@UFMeshAnimNotify@@@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@PAVUTexture@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Empty@?$TArray@VFProperty@@@@QAEXXZ@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAUFStackNodePtr@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFString@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAWarpZoneInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFLeaf@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUTexture@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAUFNameEntry@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@K@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@H@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SAInventorySpot@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???R?$TArray@PAUFNameEntry@@@@QAEAAPAUFNameEntry@@H@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUModel@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAVFLightMapIndex@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??SetSize@?$TArray@D@@QAEXH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT __CTA2PAD
xdata$x	SEGMENT DWORD USE32 PUBLIC 'CONST'
xdata$x	ENDS
;	COMDAT ?__FUNC_NAME__@?2???6@YAAAVFArchive@@AAV1@AAV?$TArray@UFMeshAnimNotify@@@@@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??FIntersectPlanes2@@YAHAAVFVector@@0ABVFPlane@@1@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@VFReachSpec@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXIAAVFMemStack@@W4EMemZeroed@@HH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SALevelInfo@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMeshAnimSeq@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUTextBuffer@@6BUObject@@@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SACamera@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7FLightManagerBase@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??Remove@?$TArray@UFMeshVertConnect@@@@QAEXHH@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT __TI2PAD
xdata$x	SEGMENT DWORD USE32 PUBLIC 'CONST'
xdata$x	ENDS
;	COMDAT ??_SAProjectile@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_SUClass@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?__FUNC_NAME__@?2??FIntersectPlanes3@@YAHAAVFVector@@ABVFPlane@@11@Z@4PBDB
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
FLAT	GROUP _DATA, CONST, _BSS, drectve, xdata$x
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif
drectve	SEGMENT
$SG15128 DB	'-INCLUDE:___@@_PchSym_@00@UpormtlmhUivmwviUhixUivovzhvUi'
	DB	'vmwviOlyq@', 00H
drectve	ENDS
PUBLIC	??2@YAPAXI@Z					; operator new
PUBLIC	??_R0PAD@8					; char * `RTTI Type Descriptor'
PUBLIC	__TI2PAD
PUBLIC	__CTA2PAD
PUBLIC	__CT??_R0PAD@84
PUBLIC	??_R0PAX@8					; void * `RTTI Type Descriptor'
PUBLIC	__CT??_R0PAX@84
PUBLIC	??_C@_02DILL@?$CFs?$AA@				; `string'
PUBLIC	?__FUNC_NAME__@?2???2@YAPAXI@Z@4PBDB		; __FUNC_NAME__
PUBLIC	??_C@_03IDPP@new?$AA@				; `string'
EXTRN	__CxxThrowException@8:NEAR
EXTRN	__imp_?appUnwindf@@YAXPBDZZ:NEAR
EXTRN	__imp_?appMalloc@@YAPAXHPBD@Z:NEAR
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
EXTRN	__except_list:DWORD
EXTRN	___CxxFrameHandler:NEAR
;	COMDAT ??_R0PAD@8
; File ..\..\Core\Inc\UnFile.h
_DATA	SEGMENT
??_R0PAD@8 DD	FLAT:??_7type_info@@6B@			; char * `RTTI Type Descriptor'
	DD	00H
	DB	'.PAD', 00H
_DATA	ENDS
;	COMDAT ??_R0PAX@8
_DATA	SEGMENT
??_R0PAX@8 DD	FLAT:??_7type_info@@6B@			; void * `RTTI Type Descriptor'
	DD	00H
	DB	'.PAX', 00H
_DATA	ENDS
;	COMDAT __CT??_R0PAD@84
xdata$x	SEGMENT
__CT??_R0PAD@84 DD 01H
	DD	FLAT:??_R0PAD@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	04H
	DD	00H
xdata$x	ENDS
;	COMDAT __CT??_R0PAX@84
xdata$x	SEGMENT
__CT??_R0PAX@84 DD 01H
	DD	FLAT:??_R0PAX@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	04H
	DD	00H
xdata$x	ENDS
;	COMDAT __CTA2PAD
xdata$x	SEGMENT
__CTA2PAD DD	02H
	DD	FLAT:__CT??_R0PAD@84
	DD	FLAT:__CT??_R0PAX@84
xdata$x	ENDS
;	COMDAT __TI2PAD
xdata$x	SEGMENT
__TI2PAD DD	00H
	DD	00H
	DD	00H
	DD	FLAT:__CTA2PAD
xdata$x	ENDS
;	COMDAT ?__FUNC_NAME__@?2???2@YAPAXI@Z@4PBDB
CONST	SEGMENT
?__FUNC_NAME__@?2???2@YAPAXI@Z@4PBDB DB '"operator new"', 00H ; __FUNC_NAME__
CONST	ENDS
;	COMDAT ??_C@_02DILL@?$CFs?$AA@
_DATA	SEGMENT
??_C@_02DILL@?$CFs?$AA@ DB '%s', 00H			; `string'
_DATA	ENDS
;	COMDAT ??_C@_03IDPP@new?$AA@
_DATA	SEGMENT
??_C@_03IDPP@new?$AA@ DB 'new', 00H			; `string'
_DATA	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T17199	DD	019930520H
	DD	02H
	DD	FLAT:$T17202
	DD	01H
	DD	FLAT:$T17203
	DD	2 DUP(00H)
	ORG $+4
$T17202	DD	0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
$T17203	DD	00H
	DD	00H
	DD	01H
	DD	02H
	DD	FLAT:$T17204
	ORG $+4
$T17204	DD	00H
	DD	FLAT:??_R0PAD@8
	DD	0ffffffecH
	DD	FLAT:$L17194
	DD	00H
	DD	00H
	DD	00H
	DD	FLAT:$L17195
xdata$x	ENDS
;	COMDAT ??2@YAPAXI@Z
_TEXT	SEGMENT
_Size$ = 8
_Err$628 = -20
$T17192 = 8
__$EHRec$ = -16
??2@YAPAXI@Z PROC NEAR					; operator new, COMDAT

; 363  : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	$L17200
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	push	ecx

; 364  : 	guard( "operator new" );
; 365  : 	return appMalloc( Size, "new" );

	mov	eax, DWORD PTR _Size$[ebp]
	push	ebx
	push	esi
	push	edi
	mov	DWORD PTR __$EHRec$[ebp], esp
	push	OFFSET FLAT:??_C@_03IDPP@new?$AA@	; `string'
	push	eax
	mov	DWORD PTR __$EHRec$[ebp+12], 0
	call	DWORD PTR __imp_?appMalloc@@YAPAXHPBD@Z
	add	esp, 8

; 367  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:__except_list, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
$L17194:

; 366  : 	unguard;

	mov	ecx, DWORD PTR _Err$628[ebp]
	lea	edx, DWORD PTR $T17192[ebp]
	push	OFFSET FLAT:__TI2PAD
	push	edx
	mov	DWORD PTR $T17192[ebp], ecx
	call	__CxxThrowException@8
	mov	eax, $L626
	ret	0
$L17195:
	push	OFFSET FLAT:?__FUNC_NAME__@?2???2@YAPAXI@Z@4PBDB ; __FUNC_NAME__
	push	OFFSET FLAT:??_C@_02DILL@?$CFs?$AA@	; `string'
	call	DWORD PTR __imp_?appUnwindf@@YAXPBDZZ
	add	esp, 8
	push	0
	push	0
	call	__CxxThrowException@8
	mov	eax, $L626
	ret	0
$L626:

; 367  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	pop	edi
	pop	esi
	mov	DWORD PTR fs:__except_list, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L17200:
	mov	eax, OFFSET FLAT:$T17199
	jmp	___CxxFrameHandler
text$x	ENDS
??2@YAPAXI@Z ENDP					; operator new
PUBLIC	??3@YAXPAX@Z					; operator delete
PUBLIC	?__FUNC_NAME__@?2???3@YAXPAX@Z@4PBDB		; __FUNC_NAME__
EXTRN	__imp_?appFree@@YAXPAX@Z:NEAR
;	COMDAT ?__FUNC_NAME__@?2???3@YAXPAX@Z@4PBDB
; File ..\..\Core\Inc\UnFile.h
CONST	SEGMENT
?__FUNC_NAME__@?2???3@YAXPAX@Z@4PBDB DB '"operator delete"', 00H ; __FUNC_NAME__
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T17213	DD	019930520H
	DD	02H
	DD	FLAT:$T17215
	DD	01H
	DD	FLAT:$T17216
	DD	2 DUP(00H)
	ORG $+4
$T17215	DD	0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
$T17216	DD	00H
	DD	00H
	DD	01H
	DD	02H
	DD	FLAT:$T17217
	ORG $+4
$T17217	DD	00H
	DD	FLAT:??_R0PAD@8
	DD	0ffffffecH
	DD	FLAT:$L17210
	DD	00H
	DD	00H
	DD	00H
	DD	FLAT:$L17211
xdata$x	ENDS
;	COMDAT ??3@YAXPAX@Z
_TEXT	SEGMENT
_Ptr$ = 8
_Err$635 = -20
$T17208 = 8
__$EHRec$ = -16
??3@YAXPAX@Z PROC NEAR					; operator delete, COMDAT

; 369  : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	$L17214
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	push	ecx

; 370  : 	guard( "operator delete" );
; 371  : 	appFree( Ptr );

	mov	eax, DWORD PTR _Ptr$[ebp]
	push	ebx
	push	esi
	push	edi
	mov	DWORD PTR __$EHRec$[ebp], esp
	push	eax
	mov	DWORD PTR __$EHRec$[ebp+12], 0
	call	DWORD PTR __imp_?appFree@@YAXPAX@Z
	add	esp, 4

; 373  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:__except_list, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
$L17210:

; 372  : 	unguard;

	mov	ecx, DWORD PTR _Err$635[ebp]
	lea	edx, DWORD PTR $T17208[ebp]
	push	OFFSET FLAT:__TI2PAD
	push	edx
	mov	DWORD PTR $T17208[ebp], ecx
	call	__CxxThrowException@8
	mov	eax, $L634
	ret	0
$L17211:
	push	OFFSET FLAT:?__FUNC_NAME__@?2???3@YAXPAX@Z@4PBDB ; __FUNC_NAME__
	push	OFFSET FLAT:??_C@_02DILL@?$CFs?$AA@	; `string'
	call	DWORD PTR __imp_?appUnwindf@@YAXPBDZZ
	add	esp, 8
	push	0
	push	0
	call	__CxxThrowException@8
	mov	eax, $L634
	ret	0
$L634:

; 373  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	pop	edi
	pop	esi
	mov	DWORD PTR fs:__except_list, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L17214:
	mov	eax, OFFSET FLAT:$T17213
	jmp	___CxxFrameHandler
text$x	ENDS
??3@YAXPAX@Z ENDP					; operator delete
PUBLIC	??_H@YGXPAXIHP6EX0@Z@Z				; `vector constructor iterator'
;	COMDAT ??_H@YGXPAXIHP6EX0@Z@Z
_TEXT	SEGMENT
___t$ = 8
___s$ = 12
___n$ = 16
___f$ = 20
??_H@YGXPAXIHP6EX0@Z@Z PROC NEAR			; `vector constructor iterator', COMDAT
	mov	eax, DWORD PTR ___n$[esp-4]
	dec	eax
	js	SHORT $L10026
	push	edi
	push	esi
	mov	esi, DWORD PTR ___t$[esp+4]
	push	ebp
	mov	ebp, DWORD PTR ___s$[esp+8]
	push	ebx
	mov	ebx, DWORD PTR ___f$[esp+12]
	lea	edi, DWORD PTR [eax+1]
$L10025:
	mov	ecx, esi
	call	ebx
	add	esi, ebp
	dec	edi
	jne	SHORT $L10025
	pop	ebx
	pop	ebp
	pop	esi
	pop	edi
$L10026:
	ret	16					; 00000010H
??_H@YGXPAXIHP6EX0@Z@Z ENDP				; `vector constructor iterator'
_TEXT	ENDS
PUBLIC	??1URender@@UAE@XZ				; URender::~URender
PUBLIC	??_GURender@@UAEPAXI@Z				; URender::`scalar deleting destructor'
EXTRN	__imp_??3UObject@@SAXPAXI@Z:NEAR
;	COMDAT ??_GURender@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8
??_GURender@@UAEPAXI@Z PROC NEAR			; URender::`scalar deleting destructor', COMDAT
	push	esi
	mov	esi, ecx
	call	??1URender@@UAE@XZ			; URender::~URender
	test	BYTE PTR ___flags$[esp], 1
	je	SHORT $L15118
	push	240					; 000000f0H
	push	esi
	call	DWORD PTR __imp_??3UObject@@SAXPAXI@Z
	add	esp, 8
$L15118:
	mov	eax, esi
	pop	esi
	ret	4
??_GURender@@UAEPAXI@Z ENDP				; URender::`scalar deleting destructor'
_TEXT	ENDS
PUBLIC	??_7URender@@6BUObject@@@			; URender::`vftable'
PUBLIC	??_7URender@@6BFExec@@@				; URender::`vftable'
PUBLIC	??_EURender@@UAEPAXI@Z				; URender::`vector deleting destructor'
EXTRN	__imp_??1URenderBase@@UAE@XZ:NEAR
EXTRN	__imp_??_7URenderBase@@6BUObject@@@:BYTE
EXTRN	__imp_??_7URenderBase@@6BFExec@@@:DWORD
EXTRN	__imp_??1UObject@@UAE@XZ:NEAR
EXTRN	__imp_??1USubsystem@@UAE@XZ:NEAR
EXTRN	__imp_??_7USubsystem@@6BUObject@@@:BYTE
EXTRN	__imp_??_7USubsystem@@6BFExec@@@:DWORD
EXTRN	__imp_?ConditionalDestroy@UObject@@QAEXXZ:NEAR
EXTRN	?QueryInterface@UObject@@UAGKABVFGuid@@PAPAX@Z:NEAR ; UObject::QueryInterface
EXTRN	?AddRef@UObject@@UAGKXZ:NEAR			; UObject::AddRef
EXTRN	?Release@UObject@@UAGKXZ:NEAR			; UObject::Release
EXTRN	?ProcessEvent@UObject@@UAEXVFName@@PAX@Z:NEAR	; UObject::ProcessEvent
EXTRN	?ProcessState@UObject@@UAEXM@Z:NEAR		; UObject::ProcessState
EXTRN	?CallInternal@UObject@@UAEXAAUFExecStack@@@Z:NEAR ; UObject::CallInternal
EXTRN	?ExportToFile@UObject@@UAEHPBD@Z:NEAR		; UObject::ExportToFile
EXTRN	?CRC@UObject@@UAEKXZ:NEAR			; UObject::CRC
EXTRN	?MemUsage@UObject@@UAEHXZ:NEAR			; UObject::MemUsage
EXTRN	?Modify@UObject@@UAEXXZ:NEAR			; UObject::Modify
EXTRN	?Export@UObject@@UAEXAAVFOutputDevice@@PBDH@Z:NEAR ; UObject::Export
EXTRN	?PostLoad@UObject@@UAEXK@Z:NEAR			; UObject::PostLoad
EXTRN	?Serialize@UObject@@UAEXAAVFArchive@@@Z:NEAR	; UObject::Serialize
EXTRN	?Lock@UObject@@UAEHK@Z:NEAR			; UObject::Lock
EXTRN	?Unlock@UObject@@UAEXK@Z:NEAR			; UObject::Unlock
EXTRN	?GotoState@UObject@@UAEHVFName@@@Z:NEAR		; UObject::GotoState
EXTRN	?GotoLabel@UObject@@UAEHVFName@@@Z:NEAR		; UObject::GotoLabel
EXTRN	?InitExecution@UObject@@UAEXXZ:NEAR		; UObject::InitExecution
EXTRN	?BeginExecution@UObject@@UAEXXZ:NEAR		; UObject::BeginExecution
EXTRN	?ShutdownAfterError@UObject@@UAEXXZ:NEAR	; UObject::ShutdownAfterError
EXTRN	?PreEditChange@UObject@@UAEXXZ:NEAR		; UObject::PreEditChange
EXTRN	?PostEditChange@UObject@@UAEXXZ:NEAR		; UObject::PostEditChange
EXTRN	?Destroy@URender@@UAEXXZ:NEAR			; URender::Destroy
EXTRN	?Init@URender@@UAEXPAVUEngine@@@Z:NEAR		; URender::Init
EXTRN	?Exec@URender@@UAEHPBDPAVFOutputDevice@@@Z:NEAR	; URender::Exec
EXTRN	?PreRender@URender@@UAEXPAUFSceneNode@@@Z:NEAR	; URender::PreRender
EXTRN	?PostRender@URender@@UAEXPAUFSceneNode@@@Z:NEAR	; URender::PostRender
EXTRN	?DrawWorld@URender@@UAEXPAUFSceneNode@@@Z:NEAR	; URender::DrawWorld
EXTRN	?Deproject@URender@@UAEHPAUFSceneNode@@HHAAVFVector@@@Z:NEAR ; URender::Deproject
EXTRN	?Project@URender@@UAEHPAUFSceneNode@@ABVFVector@@AAM2PAM@Z:NEAR ; URender::Project
EXTRN	?DrawActor@URender@@UAEXPAUFSceneNode@@PAVAActor@@@Z:NEAR ; URender::DrawActor
EXTRN	?GetVisibleSurfs@URender@@UAEXPAVUViewport@@AAV?$TArray@H@@@Z:NEAR ; URender::GetVisibleSurfs
EXTRN	?DrawLevelActors@URender@@UAEXPAUFSceneNode@@PAVAActor@@@Z:NEAR ; URender::DrawLevelActors
EXTRN	?BoundVisible@URender@@UAEHPAUFSceneNode@@PAVFBox@@PAVFSpanBuffer@@AAUFScreenBounds@@@Z:NEAR ; URender::BoundVisible
EXTRN	?GlobalLighting@URender@@UAEXHPAVAActor@@AAMAAVFPlane@@@Z:NEAR ; URender::GlobalLighting
EXTRN	?CreateMasterFrame@URender@@UAEPAUFSceneNode@@PAVUViewport@@VFVector@@VFRotation@@PAUFScreenBounds@@@Z:NEAR ; URender::CreateMasterFrame
EXTRN	?CreateChildFrame@URender@@UAEPAUFSceneNode@@PAU2@PAVFSpanBuffer@@PAVULevel@@HHMABVFPlane@@ABVFCoords@@MPAUFScreenBounds@@@Z:NEAR ; URender::CreateChildFrame
EXTRN	?Draw2DClippedLine@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z:NEAR ; URender::Draw2DClippedLine
EXTRN	?FunctionIsRemote@UObject@@UAEHAAUFStackNodePtr@@@Z:NEAR ; UObject::FunctionIsRemote
EXTRN	?IsPendingKill@UObject@@UAEHXZ:NEAR		; UObject::IsPendingKill
EXTRN	?Draw3DLine@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z:NEAR ; URender::Draw3DLine
EXTRN	?DrawCircle@URender@@UAEXPAUFSceneNode@@VFPlane@@KAAVFVector@@M@Z:NEAR ; URender::DrawCircle
EXTRN	?DrawBox@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z:NEAR ; URender::DrawBox
;	COMDAT ??_7URender@@6BUObject@@@
; File ..\..\Core\Inc\UnCorObj.h
CONST	SEGMENT
??_7URender@@6BUObject@@@ DD FLAT:?QueryInterface@UObject@@UAGKABVFGuid@@PAPAX@Z ; URender::`vftable'
	DD	FLAT:?AddRef@UObject@@UAGKXZ
	DD	FLAT:?Release@UObject@@UAGKXZ
	DD	FLAT:??_EURender@@UAEPAXI@Z
	DD	FLAT:?ProcessEvent@UObject@@UAEXVFName@@PAX@Z
	DD	FLAT:?ProcessState@UObject@@UAEXM@Z
	DD	FLAT:?CallInternal@UObject@@UAEXAAUFExecStack@@@Z
	DD	FLAT:?FunctionIsRemote@UObject@@UAEHAAUFStackNodePtr@@@Z
	DD	FLAT:?ExportToFile@UObject@@UAEHPBD@Z
	DD	FLAT:?CRC@UObject@@UAEKXZ
	DD	FLAT:?MemUsage@UObject@@UAEHXZ
	DD	FLAT:?Modify@UObject@@UAEXXZ
	DD	FLAT:?Export@UObject@@UAEXAAVFOutputDevice@@PBDH@Z
	DD	FLAT:?PostLoad@UObject@@UAEXK@Z
	DD	FLAT:?Destroy@URender@@UAEXXZ
	DD	FLAT:?Serialize@UObject@@UAEXAAVFArchive@@@Z
	DD	FLAT:?Lock@UObject@@UAEHK@Z
	DD	FLAT:?Unlock@UObject@@UAEXK@Z
	DD	FLAT:?IsPendingKill@UObject@@UAEHXZ
	DD	FLAT:?GotoState@UObject@@UAEHVFName@@@Z
	DD	FLAT:?GotoLabel@UObject@@UAEHVFName@@@Z
	DD	FLAT:?InitExecution@UObject@@UAEXXZ
	DD	FLAT:?BeginExecution@UObject@@UAEXXZ
	DD	FLAT:?ShutdownAfterError@UObject@@UAEXXZ
	DD	FLAT:?PreEditChange@UObject@@UAEXXZ
	DD	FLAT:?PostEditChange@UObject@@UAEXXZ
	DD	FLAT:?Init@URender@@UAEXPAVUEngine@@@Z
	DD	FLAT:?PreRender@URender@@UAEXPAUFSceneNode@@@Z
	DD	FLAT:?PostRender@URender@@UAEXPAUFSceneNode@@@Z
	DD	FLAT:?CreateMasterFrame@URender@@UAEPAUFSceneNode@@PAVUViewport@@VFVector@@VFRotation@@PAUFScreenBounds@@@Z
	DD	FLAT:?CreateChildFrame@URender@@UAEPAUFSceneNode@@PAU2@PAVFSpanBuffer@@PAVULevel@@HHMABVFPlane@@ABVFCoords@@MPAUFScreenBounds@@@Z
	DD	FLAT:?DrawWorld@URender@@UAEXPAUFSceneNode@@@Z
	DD	FLAT:?DrawActor@URender@@UAEXPAUFSceneNode@@PAVAActor@@@Z
	DD	FLAT:?Project@URender@@UAEHPAUFSceneNode@@ABVFVector@@AAM2PAM@Z
	DD	FLAT:?Deproject@URender@@UAEHPAUFSceneNode@@HHAAVFVector@@@Z
	DD	FLAT:?DrawLevelActors@URender@@UAEXPAUFSceneNode@@PAVAActor@@@Z
	DD	FLAT:?BoundVisible@URender@@UAEHPAUFSceneNode@@PAVFBox@@PAVFSpanBuffer@@AAUFScreenBounds@@@Z
	DD	FLAT:?GetVisibleSurfs@URender@@UAEXPAVUViewport@@AAV?$TArray@H@@@Z
	DD	FLAT:?GlobalLighting@URender@@UAEXHPAVAActor@@AAMAAVFPlane@@@Z
	DD	FLAT:?Draw2DClippedLine@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z
	DD	FLAT:?Draw3DLine@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z
	DD	FLAT:?DrawCircle@URender@@UAEXPAUFSceneNode@@VFPlane@@KAAVFVector@@M@Z
	DD	FLAT:?DrawBox@URender@@UAEXPAUFSceneNode@@VFPlane@@KVFVector@@2@Z
CONST	ENDS
;	COMDAT ??_7URender@@6BFExec@@@
CONST	SEGMENT
??_7URender@@6BFExec@@@ DD FLAT:?Exec@URender@@UAEHPBDPAVFOutputDevice@@@Z ; URender::`vftable'
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T17234	DD	019930520H
	DD	03H
	DD	FLAT:$T17236
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T17236	DD	0ffffffffH
	DD	FLAT:$L17225
	DD	0ffffffffH
	DD	FLAT:$L17227
	DD	0ffffffffH
	DD	FLAT:$L17229
xdata$x	ENDS
;	COMDAT ??1URender@@UAE@XZ
_TEXT	SEGMENT
_this$ = -16
__$EHRec$ = -12
??1URender@@UAE@XZ PROC NEAR				; URender::~URender, COMDAT

; 418  : 	DECLARE_CLASS(URender,URenderBase)

	push	-1
	push	$L17235
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	push	esi
	mov	esi, ecx
	push	edi
	mov	DWORD PTR _this$[esp+24], esi
	mov	DWORD PTR [esi], OFFSET FLAT:??_7URender@@6BUObject@@@ ; URender::`vftable'
	mov	DWORD PTR [esi+88], OFFSET FLAT:??_7URender@@6BFExec@@@ ; URender::`vftable'
	mov	edi, DWORD PTR __imp_?ConditionalDestroy@UObject@@QAEXXZ
	mov	DWORD PTR __$EHRec$[esp+32], 0
	call	edi
	mov	eax, DWORD PTR __imp_??_7URenderBase@@6BUObject@@@
	mov	ecx, DWORD PTR __imp_??_7URenderBase@@6BFExec@@@
	mov	DWORD PTR [esi], eax
	mov	DWORD PTR [esi+88], ecx
	mov	ecx, esi
	mov	DWORD PTR __$EHRec$[esp+32], 1
	call	edi
	mov	edx, DWORD PTR __imp_??_7USubsystem@@6BUObject@@@
	mov	eax, DWORD PTR __imp_??_7USubsystem@@6BFExec@@@
	mov	DWORD PTR [esi], edx
	mov	DWORD PTR [esi+88], eax
	mov	ecx, esi
	mov	DWORD PTR __$EHRec$[esp+32], 2
	call	edi
	mov	ecx, esi
	mov	DWORD PTR __$EHRec$[esp+32], -1
	call	DWORD PTR __imp_??1UObject@@UAE@XZ
	mov	ecx, DWORD PTR __$EHRec$[esp+24]
	pop	edi
	mov	DWORD PTR fs:__except_list, ecx
	pop	esi
	add	esp, 16					; 00000010H
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L17225:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	DWORD PTR __imp_??1URenderBase@@UAE@XZ
$L17227:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	DWORD PTR __imp_??1USubsystem@@UAE@XZ
$L17229:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	DWORD PTR __imp_??1UObject@@UAE@XZ
$L17235:
	mov	eax, OFFSET FLAT:$T17234
	jmp	___CxxFrameHandler
text$x	ENDS
??1URender@@UAE@XZ ENDP					; URender::~URender
EXTRN	??_M@YGXPAXIHP6EX0@Z@Z:NEAR			; `eh vector destructor iterator'
;	COMDAT ??_EURender@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8
??_EURender@@UAEPAXI@Z PROC NEAR			; URender::`vector deleting destructor', COMDAT
	push	ebx
	mov	bl, BYTE PTR ___flags$[esp]
	push	esi
	push	edi
	test	bl, 2
	mov	esi, ecx
	je	SHORT $L15121
	mov	eax, DWORD PTR [esi-4]
	lea	edi, DWORD PTR [esi-4]
	push	OFFSET FLAT:??1URender@@UAE@XZ		; URender::~URender
	push	eax
	push	240					; 000000f0H
	push	esi
	call	??_M@YGXPAXIHP6EX0@Z@Z			; `eh vector destructor iterator'
	push	edi
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
	mov	eax, esi
	pop	edi
	pop	esi
	pop	ebx
	ret	4
$L15121:
	mov	ecx, esi
	call	??1URender@@UAE@XZ			; URender::~URender
	test	bl, 1
	je	SHORT $L15124
	push	240					; 000000f0H
	push	esi
	call	DWORD PTR __imp_??3UObject@@SAXPAXI@Z
	add	esp, 8
$L15124:
	mov	eax, esi
	pop	edi
	pop	esi
	pop	ebx
	ret	4
??_EURender@@UAEPAXI@Z ENDP				; URender::`vector deleting destructor'
_TEXT	ENDS
END
